# Generated by Django 4.0.3 on 2022-03-09 16:44

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accomodation',
            name='point_of_interest',
        ),
        migrations.RemoveField(
            model_name='art_culture',
            name='point_of_interest',
        ),
        migrations.RemoveField(
            model_name='entertainment',
            name='point_of_interest',
        ),
        migrations.RemoveField(
            model_name='food',
            name='point_of_interest',
        ),
        migrations.RemoveField(
            model_name='nature',
            name='point_of_interest',
        ),
        migrations.RemoveField(
            model_name='sightseeing',
            name='point_of_interest',
        ),
        migrations.AddField(
            model_name='accomodation',
            name='neighborhood',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.neighborhood'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='art_culture',
            name='neighborhood',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.neighborhood'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entertainment',
            name='neighborhood',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.neighborhood'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='food',
            name='neighborhood',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.neighborhood'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nature',
            name='neighborhood',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.neighborhood'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sightseeing',
            name='neighborhood',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.neighborhood'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='accomodation',
            name='price',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='art_culture',
            name='price',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='entertainment',
            name='price',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='food',
            name='price',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='sightseeing',
            name='price',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.DeleteModel(
            name='Point_of_Interest',
        ),
    ]
