# Generated by Django 4.0.3 on 2022-03-09 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_rename_accomodation_accommodation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='neighborhood',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.neighborhood'),
            preserve_default=False,
        ),
    ]
