# Generated by Django 4.0.3 on 2022-03-09 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_food_neighborhood'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entertainment',
            name='price',
        ),
    ]
