# Generated by Django 4.0.3 on 2022-03-10 00:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_remove_entertainment_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Point_Of_Interest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('interest_category', models.CharField(max_length=100)),
                ('type_of', models.CharField(max_length=100)),
                ('image', models.CharField(max_length=300)),
                ('description', models.TextField(max_length=300)),
                ('neighborhood', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.neighborhood')),
            ],
        ),
        migrations.RemoveField(
            model_name='art_culture',
            name='neighborhood',
        ),
        migrations.RemoveField(
            model_name='entertainment',
            name='neighborhood',
        ),
        migrations.RemoveField(
            model_name='food',
            name='neighborhood',
        ),
        migrations.RemoveField(
            model_name='nature',
            name='neighborhood',
        ),
        migrations.RemoveField(
            model_name='sightseeing',
            name='neighborhood',
        ),
        migrations.DeleteModel(
            name='Accommodation',
        ),
        migrations.DeleteModel(
            name='Art_Culture',
        ),
        migrations.DeleteModel(
            name='Entertainment',
        ),
        migrations.DeleteModel(
            name='Food',
        ),
        migrations.DeleteModel(
            name='Nature',
        ),
        migrations.DeleteModel(
            name='SightSeeing',
        ),
    ]
