# Generated by Django 4.0.3 on 2022-03-10 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_alter_point_of_interest_type_of'),
    ]

    operations = [
        migrations.AlterField(
            model_name='point_of_interest',
            name='image',
            field=models.CharField(max_length=400),
        ),
    ]
