# Generated by Django 4.0.3 on 2022-03-10 01:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_alter_point_of_interest_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='point_of_interest',
            name='price',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)]),
        ),
        migrations.AlterField(
            model_name='point_of_interest',
            name='image',
            field=models.CharField(max_length=300),
        ),
    ]
