# Generated by Django 4.0.3 on 2022-03-16 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_remove_review_rating_review_point_of_interest_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='point_of_interest',
        ),
        migrations.DeleteModel(
            name='Point_Of_Interest',
        ),
    ]
