# Generated by Django 4.0.3 on 2022-03-16 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_remove_review_point_of_interest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='interest_id',
            field=models.CharField(default=1, max_length=220),
            preserve_default=False,
        ),
    ]
