# Generated by Django 4.0.3 on 2022-03-17 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_review_interest_id'),
        ('main_app', '0012_review_point_of_interest_id'),
    ]

    operations = [
    ]
