# Generated by Django 4.0.3 on 2022-03-17 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_merge_20220317_1543'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='interest_id',
        ),
        migrations.AlterField(
            model_name='review',
            name='point_of_interest_id',
            field=models.CharField(max_length=220, null=True),
        ),
    ]
