# Generated by Django 4.0.3 on 2022-03-23 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0020_alter_itinerary_points_of_interest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itinerary',
            name='points_of_interest_id',
        ),
        migrations.RemoveField(
            model_name='itinerary',
            name='points_of_interest_name',
        ),
    ]
